# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
    behave:


services:
    couchdb01:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb01
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "5984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer0.org1.example.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb01:5984
        depends_on:
            - orderer0.example.com
            - couchdb01

    couchdb02:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb02
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "6984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer0.org2.example.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb02:5984
        depends_on:
            - orderer0.example.com
            - couchdb02

    couchdb11:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb11
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "7984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer1.org1.example.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb11:5984
        depends_on:
            - orderer0.example.com
            - couchdb11

    couchdb12:
        extends:
            file: docker-compose-base.yml
            service: couchdb
        container_name: couchdb12
        # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
        # for example map it to utilize Fauxton User Interface in dev environments.
        ports:
          - "8984:5984"
        networks:
          behave:
             aliases:
               - ${CORE_PEER_NETWORKID}

    peer1.org2.example.com:
        environment:
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb12:5984
        depends_on:
            - orderer0.example.com
            - couchdb12
