apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ $.Values.namespace }}
  labels:
    name: {{ .Release.Name }}-db
    app.kubernetes.io/name: {{ .Release.Name }}-db
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}  
  annotations: 
    {{- toYaml .Values.annotations | nindent 6 }}      
spec:
  type: {{ .Values.db.service.type }}
  selector:
    app: {{ .Release.Name }}-db
  ports:
  - port: {{ .Values.db.service.port | default 5432 }}
    targetPort: {{ .Values.db.service.port | default 5432 }}
