
{{- if .Values.explorer.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-app-ingress
  namespace: {{ $.Values.namespace }}
  labels:
    name: {{ .Release.Name }}-app
    app.kubernetes.io/name: {{ .Release.Name }}-app
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}   
  annotations: {{- toYaml .Values.explorer.ingress.annotations | nindent 6 }}   

spec:

  rules:
    - host: {{ .Values.explorer.ingress.hosts }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-app
                port:
                  number: {{ .Values.explorer.service.port | default 8080 }}
            path: {{ .Values.explorer.ingress.path | default ("/")}}
            pathType: Prefix        
{{- end }}              
