name: build

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install server dependencies
      run: npm install

    - name: build server
      run: npm run build

    - name: install client dependencies
      run: npm install --prefix client

      
    - name: build client 
      run: CI=false npm run build --prefix client     #warnning are considered as failed build, skipping warnings 

